/*
Number Guessing Game 

The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:

1.The system generates a random number from a given range, say 1 to 100.
2.The user is prompted to enter their given number in a displayed dialogue box.
3.The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
4.The game continues under the user guessing the number.
5.You can also incorporate further details as:

> Limiting the number of attempts.
> Adding more rounds.
> Displaying score.
> Giving points based on the number of attempts.
*/

import java.util.Random;
import javax.swing.JOptionPane;

public class NumberGuessingGameGUI {

    public static void main(String[] args) {
        Random random = new Random();

        int lowerBound = 1;
        int upperBound = 100;
        int maxAttempts = 3;
        int totalRounds = 3;
        int totalScore = 0;

        JOptionPane.showMessageDialog(null, "Welcome to the Number Guessing Game!");

        for (int round = 1; round <= totalRounds; round++) {
            int targetNumber = random.nextInt(upperBound - lowerBound + 1) + lowerBound;
            int attempts = 0;
            int roundScore = 0;

            JOptionPane.showMessageDialog(null, "Round " + round + "\nTry to guess the number between " + lowerBound + " and " + upperBound);

            while (attempts < maxAttempts) {
                String input = JOptionPane.showInputDialog("Enter your guess (Attempt " + (attempts + 1) + "):");

                // Check if the user pressed the cancel button
                if (input == null) {
                    cancelGame();
                    return;
                }

                try {
                    int userGuess = Integer.parseInt(input);
                    attempts++;

                    if (userGuess == targetNumber) {
                        JOptionPane.showMessageDialog(null, "Congratulations! You guessed the correct number in " + attempts + " attempts.");
                        roundScore = maxAttempts - attempts + 1;
                        break;
                    } else if (userGuess < targetNumber) {
                        JOptionPane.showMessageDialog(null, "Too low! Try again.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Too high! Try again.");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.");
                }
            }

            if (attempts == maxAttempts) {
                JOptionPane.showMessageDialog(null, "Sorry, you've run out of attempts. The correct number was: " + targetNumber);
            }

            JOptionPane.showMessageDialog(null, "Round " + round + " Score: " + roundScore);

            totalScore += roundScore;

            // Ask if the user wants to continue or cancel
            int choice = JOptionPane.showConfirmDialog(null, "Do you want to continue to the next round?", "Continue or Cancel", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                cancelGame();
                return;
            }
        }

        JOptionPane.showMessageDialog(null, "Total Score: " + totalScore);
    }

    private static void cancelGame() {
        JOptionPane.showMessageDialog(null, "Game cancelled. Goodbye!");
        System.exit(0);
    }
}
